# production:
#   adapter: postgresql
#   url: <%= ENV['TOL_URL'] %>
#   hostname: <%= ENV['TOL_URL'] %>
#   username: <%= ENV['DB_USER'] %>
#   password: <%= ENV['DB_PASSWORD'] %>
#   database: <%= ENV['TOL_DB'] %>
#   pool: 5
#   timeout: 5000
#   port: 5432

development:
  adapter: postgresql
  encoding: unicode
  database: TreeOfLife_development
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: TreeOfLife_test
  pool: 5
  host: localhost
  password:
