production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: TreeOfLife_development
  host: localhost
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: TreeOfLife_test
  pool: 5
  host: localhost
  password:
