development:
  adapter: postgresql
  database: treeoflife_dev
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: treeoflife_test
  pool: 5
  timeout: 5000
  host: localhost
