production:
  adapter: postgresql
  url: postgres://cokgniqsoedwqe:K-uMxJmqsMnn970QkPxAnBtnXf@ec2-54-243-48-227.compute-1.amazonaws.com:5432/d8upkhenvlh40m
  hostname: ec2-54-243-48-227.compute-1.amazonaws.com
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: d8upkhenvlh40m
  pool: 5
  timeout: 5000
  port: 5432

development:
  adapter: postgresql
  host: localhost
  database: TreeOfLife_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: TreeOfLife_test
  pool: 5
  timeout: 5000
